### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by FabriMC** [Ajneb97/ConditionalEvents#21]
[23:55:14] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:55:19] [ServerMain/INFO]: Loaded 7 recipes
[23:55:22] [Server thread/INFO]: Starting minecraft server version 1.19.4
[23:55:22] [Server thread/INFO]: Loading properties
[23:55:23] [Server thread/INFO]: This server is running Paper version git-Paper-542 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: fa8fa1c)
[23:55:23] [Server thread/INFO]: Server Ping Player Sample Count: 12
[23:55:23] [Server thread/INFO]: Using 4 threads for Netty based IO
[23:55:23] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[23:55:23] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[23:55:24] [Server thread/INFO]: Default game type: CREATIVE
[23:55:24] [Server thread/INFO]: Generating keypair
[23:55:24] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:26383
[23:55:24] [Server thread/INFO]: Using epoll channel type
[23:55:24] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[23:55:24] [Server thread/INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[23:55:27] [Server thread/INFO]: [ViaVersion] Loading server plugin ViaVersion v4.7.0
[23:55:27] [Server thread/INFO]: [ViaVersion] ViaVersion 4.7.0 is now loaded. Registering protocol transformers and injecting...
[23:55:28] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[23:55:29] [Via-Mappingloader-0/INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[23:55:29] [Server thread/INFO]: [ViaBackwards] Loading translations...
[23:55:29] [Server thread/INFO]: [ViaBackwards] Registering protocols...
[23:55:30] [Server thread/INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.98
[23:55:31] [Server thread/INFO]: [Vault] Loading server plugin Vault v1.7.3-b131
[23:55:31] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.0.0
[23:55:35] [Server thread/INFO]: [ViaBackwards] Loading server plugin ViaBackwards v4.7.0
[23:55:35] [Server thread/INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.3
[23:55:35] [Server thread/INFO]: [Essentials] Loading server plugin Essentials v2.20.0-dev+56-fd49b70
[23:55:35] [Server thread/INFO]: [AlonsoLib] Loading server plugin AlonsoLib v0.1-BETA
[23:55:35] [Server thread/INFO]: [SkinsRestorer] Loading server plugin SkinsRestorer v14.2.12
[23:55:35] [Server thread/INFO]: [TAB] Loading server plugin TAB v3.3.2
[23:55:35] [Server thread/INFO]: [ViaRewind] Loading server plugin ViaRewind v2.0.3
[23:55:35] [Server thread/INFO]: [ClimateChange] Loading server plugin ClimateChange v3.3.0
[23:55:35] [Server thread/INFO]: [DeluxeMenus] Loading server plugin DeluxeMenus v1.13.7-Release
[23:55:35] [Server thread/INFO]: [DeluxeMenus] NMS hook has been setup successfully!
[23:55:35] [Server thread/INFO]: [AlonsoChat] Loading server plugin AlonsoChat v0.1-BETA
[23:55:35] [Server thread/INFO]: [ConditionalEvents] Loading server plugin ConditionalEvents v4.35.3
[23:55:35] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:55:35] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.98
[23:55:40] [Server thread/INFO]:         __    
[23:55:40] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.98
[23:55:40] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[23:55:40] [Server thread/INFO]: 
[23:55:40] [Server thread/INFO]: [LuckPerms] Loading configuration...
[23:55:42] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[23:55:45] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[23:55:45] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[23:55:46] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 8610ms)
[23:55:46] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[23:55:47] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[23:55:47] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[23:55:47] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[23:55:48] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[23:55:48] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.0.0
[23:55:48] [Server thread/INFO]: [AlonsoLib] Enabling AlonsoLib v0.1-BETA
[23:55:49] [Server thread/INFO]: [AlonsoLib] Hex colors are available! Ready for RGB..
[23:55:49] [Server thread/INFO]:      _   _                  _    _ _       Running v0.1-BETA
[23:55:49] [Server thread/INFO]:     /_\ | |___ _ _  ___ ___| |  (_) |__    Server Paper vgit-Paper-542 (MC: 1.19.4)
[23:55:49] [Server thread/INFO]:    / _ \| / _ \ ' \(_-</ _ \ |__| | '_ \   Using Adventure-bukkit v4.2.0 & Adventure-minimessagev4.12.0
[23:55:49] [Server thread/INFO]:   /_/ \_\_\___/_||_/__/\___/____|_|_.__/   Thanks for using my plugin ❤!
[23:55:49] [Server thread/INFO]:         Developed by AlonsoAliaga
[23:55:49] [Server thread/INFO]: 
[23:55:49] [Server thread/INFO]: [ViaRewind] Enabling ViaRewind v2.0.3
[23:55:51] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[23:55:51] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[23:55:51] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[23:55:51] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[23:55:51] [Server thread/INFO]: Preparing level "world"
[23:55:54] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:55:55] [Server thread/INFO]: Time elapsed: 734 ms
[23:55:55] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.7.0
[23:55:56] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.19.4 (762)
[23:55:56] [Server thread/INFO]: [ViaBackwards] Enabling ViaBackwards v4.7.0
[23:55:57] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.3
[23:56:00] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[23:56:00] [Server thread/INFO]: [Essentials] Enabling Essentials v2.20.0-dev+56-fd49b70
[23:56:05] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[23:56:05] [Server thread/INFO]: [Essentials] No kits found to migrate.
[23:56:07] [Server thread/INFO]: [Essentials] Loaded 38132 items from items.json.
[23:56:07] [Server thread/INFO]: [Essentials] Using locale en_US
[23:56:08] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[23:56:08] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[23:56:08] [Server thread/INFO]: [Vault] [Economy] Essentials Economy hooked.
[23:56:08] [Server thread/INFO]: [Essentials] Using Vault based permissions (LuckPerms)
[23:56:08] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.2.12
[23:56:10] [Server thread/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1mDetected Minecraft [33;1mv1_19_R3[32;1m, using [33;1mMappingSpigotSkinRefresher[32;1m.[0;39m
[23:56:12] [Server thread/INFO]: [SkinsRestorer] [ACF] Enabled Asynchronous Tab Completion Support!
[23:56:12] [Server thread/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39mUsing paper join listener![0;39m
[23:56:12] [Server thread/INFO]: [TAB] Enabling TAB v3.3.2
[23:56:13] [Server thread/INFO]: [TAB] Server version: 1.19.4 (v1_19_R3)
[23:56:13] [Server thread/INFO]: [TAB] Loaded NMS hook in 206ms
[23:56:14] [Server thread/INFO]: [TAB] Enabled in 1001ms
[23:56:14] [Server thread/INFO]: [ClimateChange] Enabling ClimateChange v3.3.0
[23:56:15] [Server thread/INFO]: 

                ===================================================
                                   ClimateChange
                ===================================================

                              Current version: 3.3.0
                        You are running the latest version!

                ===================================================

[23:56:15] [Server thread/INFO]: [ClimateChange] Developed by EndlessGames.
[23:56:15] [Server thread/INFO]: [DeluxeMenus] Enabling DeluxeMenus v1.13.7-Release
[23:56:15] [Server thread/INFO]: [DeluxeMenus] Successfully hooked into PlaceholderAPI!
[23:56:17] [Server thread/INFO]: [DeluxeMenus] 8 GUI menus loaded!
[23:56:17] [Server thread/INFO]: [DeluxeMenus] You are running the latest version of DeluxeMenus!
[23:56:17] [Server thread/INFO]: [DeluxeMenus] Successfully hooked into Vault!
[23:56:17] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: deluxemenus [1.13.7-Release]
[23:56:17] [Server thread/INFO]: [AlonsoChat] Enabling AlonsoChat v0.1-BETA
[23:56:18] [Server thread/INFO]: [AlonsoChat] Old method 'setData' is not supported. Skipping data values..
[23:56:18] [Server thread/INFO]: [AlonsoChat] Max health Attribute check found. Using it..
[23:56:18] [Server thread/INFO]: [AlonsoChat] New setOwningPlayer method is available!
[23:56:18] [Server thread/INFO]: [AlonsoChat] Old ItemStack constructor is available!
[23:56:18] [Server thread/INFO]: [AlonsoChat] Inventory title with support for more than 32 characters. Skipping..
[23:56:18] [Server thread/INFO]: [AlonsoChat] Hex colors are available! Ready for RGB..
[23:56:18] [Server thread/INFO]: [AlonsoChat] Old constructor for HoverEvent found! Using it..
[23:56:18] [Server thread/INFO]: [AlonsoChat] New sendTitle method found! Using it..
[23:56:18] [Server thread/INFO]: [AlonsoChat] New setUnbreakable method found! Using it..
[23:56:18] [Server thread/INFO]: [AlonsoChat] New isUnbreakable method found! Using it..
[23:56:18] [Server thread/INFO]: [AlonsoChat] Damageable interface is available! Using it to set durability..
[23:56:18] [Server thread/INFO]: [AlonsoChat] Old setDurability method found. Using it as last alternatice..
[23:56:18] [Server thread/INFO]: [AlonsoChat] Directional interface is available! Using it to get attached block for signs..
[23:56:18] [Server thread/INFO]: [AlonsoChat] New colored material supported! Using it..
[23:56:18] [Server thread/INFO]: [AlonsoChat] SpawnFallingBlock method is BlockData!
[23:56:18] [Server thread/INFO]:     _   _                   ___ _         _    Running v0.1-BETA
[23:56:18] [Server thread/INFO]:    /_\ | |___ _ _  ___ ___ / __| |_  __ _| |_  Server Paper vgit-Paper-542 (MC: 1.19.4)
[23:56:18] [Server thread/INFO]:   / _ \| / _ \ ' \(_-</ _ \ (__| ' \/ _` |  _| Discord for support: https://alonsoaliaga.com/discord
[23:56:18] [Server thread/INFO]:  /_/ \_\_\___/_||_/__/\___/\___|_||_\__,_|\__| Thanks for using my plugin ❤!
[23:56:18] [Server thread/INFO]:         Developed by AlonsoAliaga
[23:56:18] [Server thread/INFO]: 
[23:56:18] [Server thread/INFO]: ==============================================================================================
[23:56:18] [Server thread/INFO]: [AlonsoChat] This is not a error! This is just a warning to keep in mind if you have issues!
[23:56:18] [Server thread/INFO]: [AlonsoChat] You are using a Paper fork (Paper). This plugin was made for Spigot
[23:56:18] [Server thread/INFO]: [AlonsoChat] but was (in most cases) tested with different builds of Paper and Purpur.
[23:56:18] [Server thread/INFO]: [AlonsoChat] Spigot and forks API are really similar and should be compatible, however there are
[23:56:18] [Server thread/INFO]: [AlonsoChat] some cases in which they aren't compatible. If you have issues report them to the
[23:56:18] [Server thread/INFO]: [AlonsoChat] developer instead of reviewing 1 star. Thanks in advanced!
[23:56:18] [Server thread/INFO]: [AlonsoChat] Join us in our official support server on alonsoaliaga.com/discord
[23:56:18] [Server thread/INFO]: ==============================================================================================
[23:56:18] [Server thread/INFO]: 
[23:56:18] [Server thread/INFO]: [AlonsoChat] BungeeCord action bar available. Hooking..
[23:56:18] [Server thread/INFO]: [AlonsoChat] ProtocolLib found! Checking..
[23:56:18] [Server thread/INFO]: [Auto-update] Configuration config.yml is up-to-date!
[23:56:18] [Server thread/INFO]: [AlonsoChat] Color URL regex was loaded: '(https|http):\/\/([-\w_.]+\.[a-z][\w]{1,7})(\/\S*)?'. Checking url regex..
[23:56:18] [Server thread/INFO]: [AlonsoChat] Link URL regex was loaded: '((&#[a-f0-9]{6})?(&[a-f0-9klmnor])*)?(https|http):\/\/([-\w_.]+\.[a-z][\w]{1,7})(\/\S*)?'. URL support enabled!
[23:56:18] [Server thread/INFO]: [AlonsoChat] Remember that NBTAPI is necessary for books feature! Download on https://alonsoaliaga.com/NBTAPI
[23:56:18] [Server thread/INFO]: [AlonsoChat] Successfully loaded 1 books!
[23:56:18] [Server thread/INFO]: [AlonsoChat] Options.Worlds is empty. Plugin will format messages in all worlds.
[23:56:19] [Server thread/INFO]: [AlonsoChat] Successfully loaded 4 parts for 'default' format!
[23:56:19] [Server thread/INFO]: [AlonsoChat] Successfully loaded 1 formats!
[23:56:19] [Server thread/INFO]: [AlonsoChat] PlaceholderAPI found! Hooking..
[23:56:19] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: alonsochat [0.1-BETA]
[23:56:19] [Server thread/INFO]: [ConditionalEvents] Enabling ConditionalEvents v4.35.3
[23:56:20] [Server thread/ERROR]: Error occurred while enabling ConditionalEvents v4.35.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.ProtocolManager.addPacketListener(com.comphenix.protocol.events.PacketListener)" because the return value of "com.comphenix.protocol.ProtocolLibrary.getProtocolManager()" is null
	at ce.ajneb97.managers.dependencies.ProtocolLibManager.configure(ProtocolLibManager.java:33) ~[ConditionalEvents (1).jar:?]
	at ce.ajneb97.managers.dependencies.ProtocolLibManager.<init>(ProtocolLibManager.java:29) ~[ConditionalEvents (1).jar:?]
	at ce.ajneb97.managers.DependencyManager.<init>(DependencyManager.java:36) ~[ConditionalEvents (1).jar:?]
	at ce.ajneb97.ConditionalEvents.onEnable(ConditionalEvents.java:48) ~[ConditionalEvents (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-542]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-542]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:556) ~[paper-1.19.4.jar:git-Paper-542]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:467) ~[paper-1.19.4.jar:git-Paper-542]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-542]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-542]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-542]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-542]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-542]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:56:20] [Server thread/INFO]: [ConditionalEvents] Disabling ConditionalEvents v4.35.3
[23:56:20] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling ConditionalEvents v4.35.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "ce.ajneb97.configs.ConfigsManager.getPlayerConfigsManager()" because "this.configsManager" is null
	at ce.ajneb97.ConditionalEvents.onDisable(ConditionalEvents.java:83) ~[ConditionalEvents (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.19.4.jar:git-Paper-542]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.19.4.jar:git-Paper-542]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.19.4.jar:git-Paper-542]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-542]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:556) ~[paper-1.19.4.jar:git-Paper-542]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:467) ~[paper-1.19.4.jar:git-Paper-542]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-542]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-542]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-542]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-542]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-542]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:56:21] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[23:56:21] [Server thread/INFO]: Running delayed init tasks
[23:56:21] [Server thread/INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[23:56:21] [Server thread/INFO]: Done (58.586s)! For help, type "help"
[23:56:21] [Craft Scheduler Thread - 5 - ViaVersion/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[23:56:21] [Server thread/INFO]: Timings Reset
[23:56:21] [Craft Scheduler Thread - 7 - Essentials/INFO]: [Essentials] Fetching version information...
[23:56:21] [Craft Scheduler Thread - 13 - Vault/INFO]: [Vault] Checking for Updates ... 
[23:56:22] [Craft Scheduler Thread - 13 - Vault/INFO]: [Vault] No new version available
[23:56:22] [Craft Scheduler Thread - 8 - AlonsoChat/INFO]: [AlonsoChat] Checking for updates...
[23:56:22] [Craft Scheduler Thread - 8 - AlonsoChat/INFO]: [AlonsoChat] Plugin up-to-date! You have the latest version!
[23:56:22] [Craft Scheduler Thread - 5 - SkinsRestorer/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m----------------------------------------------[0;39m
[23:56:22] [Craft Scheduler Thread - 5 - SkinsRestorer/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m    +==================+[0;39m
[23:56:22] [Craft Scheduler Thread - 5 - SkinsRestorer/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m    |   SkinsRestorer  |[0;39m
[23:56:22] [Craft Scheduler Thread - 5 - SkinsRestorer/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m    |------------------|[0;39m
[23:56:22] [Craft Scheduler Thread - 5 - SkinsRestorer/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m    |  [34;1m[4m[21mStandalone Mode[0;39m[32;1m |[0;39m
[23:56:22] [Craft Scheduler Thread - 5 - SkinsRestorer/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m    +==================+[0;39m
[23:56:22] [Craft Scheduler Thread - 5 - SkinsRestorer/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m----------------------------------------------[0;39m
[23:56:22] [Craft Scheduler Thread - 5 - SkinsRestorer/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[36;1m    Current version: [32;1m14.2.12[0;39m
[23:56:22] [Craft Scheduler Thread - 5 - SkinsRestorer/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m    This is the latest version![0;39m
[23:56:22] [Craft Scheduler Thread - 5 - SkinsRestorer/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m----------------------------------------------[0;39m
[23:56:22] [Craft Scheduler Thread - 7 - Essentials/WARN]: [Essentials] You're 51 EssentialsX dev build(s) out of date!
[23:56:22] [Craft Scheduler Thread - 7 - Essentials/WARN]: [Essentials] Download it here: https://essentialsx.net/downloads.html
[23:56:26] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: essentials [1.5.2]
[23:56:26] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.5]
[23:56:26] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: vault [1.8.1]
[23:56:26] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: changeoutput [1.2.2]
[23:56:26] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: server [2.6.2]
[23:56:27] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: world [1.2.2]
[23:56:27] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: math [2.0.2]
[23:56:27] [Server thread/INFO]: 7 placeholder hook(s) registered!

**Comment by FabriMC** [comment]
Me acabo de dar cuenta que al eliminar el ProtocolLib el ConditionalEvents carga correctamente sin soltar ningun error en la consola.

**Comment by Ajneb97** [comment]
Ve si es que el ProtocolLib esta cargando correctamente y si esta en verde al usar /plugins, porque el error es del ProtocolLib:
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.ProtocolManager.addPacketListener(com.comphenix.protocol.events.PacketListener)" because the return value of "com.comphenix.protocol.ProtocolLibrary.getProtocolManager()" is null

**Comment by FabriMC** [comment]
El ProtocolLib carga correctamente y se muestra en verde pero el conditional event se pone en rojo y manda el mismo error. PD: Soy FabriMC😥

**Comment by Ajneb97** [comment]
Tendrias que preguntar con los devs de ProtocolLib, mandandoles el mismo error ya que por lo que yo veo es este metodo el que esta arrojando null por alguna razón: com.comphenix.protocol.ProtocolLibrary.getProtocolManager()

**Comment by AlonsoAliaga** [comment]
Yo diría que envíes el log completo al cargar el servidor en un pastebin para poder asegurarse que el orden de carga es correcto

> El ProtocolLib carga correctamente y se muestra en verde pero el conditional event se pone en rojo y manda el mismo error. PD: Soy FabriMC😥
Yo diría que envies el log completo desde el inicio en un pastebin para poder ver si el orden de carga es el correcto

**Comment by yiyoperez** [comment]
Me envió este log ayer https://mclo.gs/cnZdZlV

**Comment by AlonsoAliaga** [comment]
Como dice Ajneb, esta raro, no hay indicios de que el ProtocolLib haya cargado luego de ConditionalEvents, todo indica que se cargó antes y aún así da error 😔 Lo ideal sería que les mande el log a los devs de ProtocolLib, pero no recuerdo si los del protocol lib tenian soporte en discord. Posiblemente solo respondan en Github al abrir un issue con el log completo
