### ISSUE TITLE
Continuously getting this console error

### ISSUE THREAD

**Issue by ValhallaCraft** [Ajneb97/ConditionalEvents#4]
```! [Wed 17:07:04 WARN  ConditionalEvents] Task #39932 for ConditionalEvents v4.2.2 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at ConditionalEvents .jar//ce.ajneb97.model.internal.ExecutedEvent.executeActionsFinal(ExecutedEvent.java:123)
	at ConditionalEvents .jar//ce.ajneb97.model.internal.ExecutedEvent.continueWithActions(ExecutedEvent.java:92)
	at ConditionalEvents .jar//ce.ajneb97.utils.ActionUtils$2.run(ActionUtils.java:320)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
	at java.base/java.lang.Thread.run(Thread.java:833)
  
  ```

**Comment by Ajneb97** [comment]
The to_range actions were modified, please check the new format on: https://ajneb97.gitbook.io/conditionalevents/actions/to-actions#to-range
