### ISSUE TITLE
[BUG] Resourcepack sound not working with location

### ISSUE THREAD

**Issue by IceGames23** [Ajneb97/ConditionalEvents#96]
Hello, I'm using ConditionalEvents 4.57.4 on 1.8.8 and I'm trying to execute this:
![image](https://github.com/user-attachments/assets/1914e747-2e05-4ee2-a129-f46fbda3f841)
But here's the error:
```
[03:40:38 INFO]: IceGames_ issued server command: /ce call minapvp_nexusbreak2
[03:40:38 ERROR]: Could not pass event ConditionalEventsCallEvent to ConditionalEvents v4.57.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at ce.ajneb97.utils.ActionUtils.callEvent(ActionUtils.java:881) ~[?:?]
        at ce.ajneb97.MainCommand.call(MainCommand.java:263) ~[?:?]
        at ce.ajneb97.MainCommand.onCommand(MainCommand.java:69) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:700) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1213) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1025) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:9) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:881) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-130]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void org.bukkit.World.playSound(org.bukkit.Location, java.lang.String, float, float)'
        at ce.ajneb97.utils.ActionUtils.playSoundResourcePack(ActionUtils.java:298) ~[?:?]
        at ce.ajneb97.model.internal.ExecutedEvent.executeAction(ExecutedEvent.java:292) ~[?:?]
        at ce.ajneb97.model.internal.ExecutedEvent.executeActionsFinal(ExecutedEvent.java:206) ~[?:?]
        at ce.ajneb97.model.internal.ExecutedEvent.executeActions(ExecutedEvent.java:98) ~[?:?]
        at ce.ajneb97.managers.EventsManager.checkSingularEvent(EventsManager.java:133) ~[?:?]
        at ce.ajneb97.listeners.OtherEventsListener.onConditionalEventsCallEvent(OtherEventsListener.java:86) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-130]
```

**Comment by Ajneb97** [comment]
It seems spigot 1.8.8 doesn't have a method to play a resource pack sound on a certain coordinate in a world:
https://helpch.at/docs/1.8.8/org/bukkit/World.html

You must use a higher version.
